# Generated by Django 5.2 on 2025-04-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('Автоперевозка', 'Автомобильные перевозки'), ('Мультимодальная', 'Мультимодальные перевозки'), ('Аутсорсинг', 'Аутсорсинг логистики'), ('Спецтехника', 'Спецтехника')], max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
