# Generated by Django 5.2 on 2025-04-17 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='service_type',
            field=models.CharField(choices=[('delivery', 'Грузоперевозка'), ('outsourcing', 'Аутсорсинг логистики'), ('multimodal', 'Мультимодальные перевозки'), ('special', 'Спецтехника'), ('other', 'Другое')], max_length=50, verbose_name='Тип услуги'),
        ),
    ]
