# Generated by Django 5.2 on 2025-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Unnamed', max_length=100, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='request_type',
            field=models.CharField(choices=[('local', 'Локальная автоперевозка'), ('international', 'Международная автоперевозка'), ('multimodal', 'Мультимодальная логистика'), ('outsourcing', 'Аутсорсинг логистики'), ('equipment', 'Спецтехника')], default='Unnamed', max_length=30, verbose_name='Тип заявки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
