# Generated by Django 5.2 on 2025-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_name_order_full_name_order_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='request_type',
            field=models.CharField(choices=[('cargo', 'Грузоперевозка'), ('storage', 'Складские услуги'), ('customs', 'Таможенное оформление')], max_length=20),
        ),
    ]
